import { ResumeData, TemplateInfo } from '@/types/resume';

export const TEMPLATES: TemplateInfo[] = [
  {
    id: 'classic-ats',
    name: 'Classic ATS',
    description: 'Clean single-column layout with standard headings, optimal contrast, and simple document hierarchy for high machine readability.',
    bestSuitedFor: 'General job applicants, corporate roles, traditional industries, and strict ATS systems',
    isAtsOptimized: true,
    category: 'ATS',
    accentColor: '#111827',
    features: ['Single-Column Layout', 'Standard Headings', 'High Contrast Text', 'ATS-Conscious Structure'],
  },
  {
    id: 'modern-professional',
    name: 'Modern Professional',
    description: 'Balanced visual hierarchy with a subtle blue accent, modern typography, and structured section organization.',
    bestSuitedFor: 'Software engineers, tech professionals, product managers, and corporate candidates',
    isAtsOptimized: true,
    category: 'Professional',
    accentColor: '#2563EB',
    features: ['Subtle Color Accent', 'Clean Visual Flow', 'Modern Type Scale', 'Readable Hierarchy'],
  },
  {
    id: 'graduate',
    name: 'Graduate & Fresher',
    description: 'Designed specifically to emphasize academic coursework, technical projects, internships, and core competencies.',
    bestSuitedFor: 'College students, fresh graduates, internship applicants, and entry-level professionals',
    isAtsOptimized: true,
    category: 'Student',
    accentColor: '#0F766E',
    features: ['Projects-First Hierarchy', 'Education & Coursework Focus', 'Categorized Skills', 'Internship Highlighting'],
  },
  {
    id: 'executive',
    name: 'Executive & Leadership',
    description: 'Prominently showcases executive summaries, leadership impact, strategic work history, and key business outcomes.',
    bestSuitedFor: 'Experienced professionals, team leads, engineering managers, and directors',
    isAtsOptimized: true,
    category: 'Executive',
    accentColor: '#1E293B',
    features: ['Executive Summary Focus', 'Core Competencies Grid', 'Impact-Oriented Work History', 'Refined Layout'],
  },
  {
    id: 'minimal-professional',
    name: 'Minimal Professional',
    description: 'Ultra-clean minimalist structure emphasizing generous whitespace, subtle gray dividers, and crisp modern typography.',
    bestSuitedFor: 'Business analysts, consulting, corporate roles, marketing, and minimalists',
    isAtsOptimized: true,
    category: 'Professional',
    accentColor: '#3B82F6',
    features: ['Minimalist Aesthetics', 'Generous Whitespace', 'Subtle Divider Lines', 'High Scannability'],
  },
  {
    id: 'technical-specialist',
    name: 'Technical Specialist',
    description: 'Engineered specifically for developers, data engineers, cloud architects, and IT specialists with prominent tech stacks.',
    bestSuitedFor: 'Software engineers, DevOps, cybersecurity, cloud specialists, and full-stack developers',
    isAtsOptimized: true,
    category: 'ATS',
    accentColor: '#1D4ED8',
    features: ['Technical Skills Matrix', 'Project Architecture Focus', 'Repository & Demo Links', 'Clean Code Emphasis'],
  },
];

/**
 * 100% Generic Fictional Sample Resume for Demonstrations (Police Manoj)
 */
export const FICTIONAL_SAMPLE_RESUME: ResumeData = {
  id: 'sample-resume-fictional',
  title: 'Police Manoj — Software Engineer Resume',
  lastModified: new Date().toISOString(),
  personalInfo: {
    fullName: 'Police Manoj',
    professionalTitle: 'Aspiring Software Engineer',
    email: 'police.manoj@example.com',
    phone: '+91 90000 00000',
    location: 'Hyderabad, Telangana, India',
    linkedin: 'https://linkedin.com/in/police-manoj',
    github: 'https://github.com/police-manoj',
    portfolio: 'https://policemanoj.example.dev',
  },
  summary: {
    summaryText: 'Motivated and detail-oriented Computer Science undergraduate with hands-on experience in full-stack web development, REST API design, and distributed systems. Proven track record in building practical projects and collaborating in agile team environments. Eager to contribute strong problem-solving skills and clean code to an impactful engineering team.',
    targetRole: 'Software Engineer',
    experienceLevel: 'student',
    yearsOfExperience: 'Fresher (2026)',
  },
  education: [
    {
      id: 'edu-fict-1',
      institution: 'Hyderabad Institute of Technology & Science',
      degree: 'Bachelor of Technology (B.Tech)',
      fieldOfStudy: 'Computer Science and Engineering',
      startDate: 'Aug 2022',
      endDate: 'May 2026',
      isCurrent: true,
      location: 'Hyderabad, India',
      gpa: '8.7 / 10.0 CGPA',
      relevantCoursework: 'Data Structures & Algorithms, Operating Systems, Database Management Systems, Computer Networks, Object-Oriented Programming',
      academicAchievements: 'Dean\'s Merit Award for Academic Excellence (3 semesters)',
    },
  ],
  experience: [],
  internships: [
    {
      id: 'intern-fict-1',
      organization: 'Nexora Tech Labs',
      role: 'Software Engineering Intern',
      location: 'Hyderabad, India',
      startDate: 'May 2024',
      endDate: 'Jul 2024',
      isCurrent: false,
      description: 'Collaborated with the core development team to build internal developer productivity tools and optimize backend RESTful APIs.',
      responsibilities: [
        'Engineered 6 modular REST API endpoints using Node.js and TypeScript to automate internal data aggregation.',
        'Wrote automated unit and integration test suites using Jest, boosting test coverage from 65% to 82%.',
        'Participated in daily agile standups, code reviews, and database schema optimization discussions.',
      ],
      technologiesUsed: ['TypeScript', 'Node.js', 'PostgreSQL', 'Docker', 'Jest'],
      displayUnder: 'internships',
    },
  ],
  skills: [
    {
      id: 'sk-cat-1',
      categoryName: 'Programming Languages',
      skills: ['Python', 'Java', 'TypeScript', 'JavaScript (ES6+)', 'C++', 'SQL'],
    },
    {
      id: 'sk-cat-2',
      categoryName: 'Frameworks & Web',
      skills: ['React.js', 'Next.js', 'Node.js', 'Express', 'Tailwind CSS', 'RESTful APIs'],
    },
    {
      id: 'sk-cat-3',
      categoryName: 'Databases & Tools',
      skills: ['PostgreSQL', 'MySQL', 'Redis', 'Git & GitHub', 'Docker', 'Linux / Bash'],
    },
    {
      id: 'sk-cat-4',
      categoryName: 'Core Competencies',
      skills: ['Problem Solving', 'Data Structures & Algorithms', 'Agile Methodologies', 'Technical Documentation'],
    },
  ],
  projects: [
    {
      id: 'proj-fict-1',
      projectName: 'Distributed Task Queue Engine',
      shortDescription: 'Asynchronous background task processing system with persistent Redis queues, worker health tracking, and exponential backoff.',
      technologies: ['TypeScript', 'Node.js', 'Redis', 'Docker'],
      role: 'Lead Developer',
      githubLink: 'https://github.com/police-manoj/task-queue-engine',
      startDate: 'Jan 2024',
      endDate: 'Apr 2024',
      keyContributions: [
        'Engineered high-throughput worker pool capable of processing up to 2,500 background jobs per minute with Redis streams.',
        'Implemented dead-letter queue management and automated retry policies for failed background jobs.',
        'Built real-time web monitoring dashboard displaying queue depth, latency, and active worker metrics.',
      ],
      results: 'Reduced average background job turnaround time by 35% in simulated workloads.',
    },
    {
      id: 'proj-fict-2',
      projectName: 'Real-time Markdown Collaboration Platform',
      shortDescription: 'Full-stack collaborative document workspace with live operational transformation and cursor presence.',
      technologies: ['React', 'Next.js', 'WebSockets', 'PostgreSQL', 'Tailwind CSS'],
      role: 'Full Stack Developer',
      githubLink: 'https://github.com/police-manoj/collab-markdown',
      projectLink: 'https://collab-md.example.dev',
      startDate: 'Sep 2023',
      endDate: 'Dec 2023',
      keyContributions: [
        'Built WebSocket synchronization layer allowing multiple concurrent users to edit markdown documents in real time.',
        'Implemented split-view live preview with Markdown syntax highlighting and client-side PDF export.',
      ],
      results: 'Supported 15+ concurrent editors per document with sub-50ms latency.',
    },
  ],
  certifications: [
    {
      id: 'cert-fict-1',
      certificationName: 'AWS Certified Cloud Practitioner',
      issuingOrganization: 'Amazon Web Services (AWS)',
      issueDate: 'May 2024',
      expirationDate: 'May 2027',
      credentialId: 'AWS-CCP-908124',
      credentialUrl: 'https://aws.amazon.com/verification',
    },
  ],
  achievements: [
    {
      id: 'ach-fict-1',
      achievement: 'Winner — Inter-College Hackathon 2024',
      organization: 'Tech Innovation Summit',
      date: 'Mar 2024',
      description: 'Developed an open-source accessibility web utility among 50+ participating engineering teams.',
    },
  ],
  awards: [],
  publications: [],
  languages: [
    { id: 'lang-fict-1', language: 'English', proficiency: 'Fluent' },
    { id: 'lang-fict-2', language: 'Telugu', proficiency: 'Native' },
    { id: 'lang-fict-3', language: 'Hindi', proficiency: 'Professional' },
  ],
  interests: [
    { id: 'int-fict-1', name: 'Open-source software' },
    { id: 'int-fict-2', name: 'Distributed systems' },
    { id: 'int-fict-3', name: 'System design' },
  ],
  customSections: [],
  settings: {
    templateId: 'modern-professional',
    font: 'inter',
    fontSize: 'medium',
    lineSpacing: 'normal',
    margins: 'normal',
    accentColor: '#2563EB',
    showSectionDividers: true,
  },
  enabledSections: {
    summary: true,
    education: true,
    experience: false,
    internships: true,
    skills: true,
    projects: true,
    certifications: true,
    achievements: true,
    awards: false,
    publications: false,
    languages: true,
    interests: true,
    customSections: false,
  },
};

/**
 * Clean, completely blank initial state for all new users
 */
export const EMPTY_RESUME: ResumeData = {
  id: 'new-resume',
  title: 'Untitled Resume',
  lastModified: new Date().toISOString(),
  personalInfo: {
    fullName: '',
    professionalTitle: '',
    email: '',
    phone: '',
    location: '',
    linkedin: '',
    github: '',
    portfolio: '',
    otherLink: '',
  },
  summary: {
    summaryText: '',
    targetRole: '',
    experienceLevel: 'student',
    yearsOfExperience: '',
  },
  education: [],
  experience: [],
  internships: [],
  skills: [],
  projects: [],
  certifications: [],
  achievements: [],
  awards: [],
  publications: [],
  languages: [],
  interests: [],
  customSections: [],
  settings: {
    templateId: 'classic-ats',
    font: 'inter',
    fontSize: 'medium',
    lineSpacing: 'normal',
    margins: 'normal',
    accentColor: '#111827',
    showSectionDividers: true,
  },
  enabledSections: {
    summary: true,
    education: true,
    experience: true,
    internships: true,
    skills: true,
    projects: true,
    certifications: true,
    achievements: false,
    awards: false,
    publications: false,
    languages: true,
    interests: false,
    customSections: false,
  },
};
